on: [push]

jobs:
  pages:
    name: "Deploy Sphinx documentation to Pages"
    runs-on: ubuntu-latest

    steps:
    - name: "Set up python 3.x"
      uses: actions/checkout@v3
      with:
        python-version: 3.x

    - name: "Install dependencies"
      run: |
        python -m pip install --upgrade pip
        pip install Sphinx sphinx-rtd-theme

    - name: "Run Shpinxt"
      run: |
        cd docs
        make html