name: docs_pages_workflow

on: [push]

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install Sphinx sphinx-rtd-theme Django django-handyhelpers

      - name: "Make sphinx docs"
        run: |
          make -C docs html
          touch docs/build/html/.nojekyll

      - name: "Init new report is dist folder and commit generated files"
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "deploy"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
