name: docs_pages_workflow

on: [push]

jobs:

  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: "Set up python 3.x"
        uses: actions/checkout@v3
        with:
          python-version: 3.x

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install Sphinx sphinx-rtd-theme Django django-handyhelpers

      - name: "Make sphinx docs"
        run: make -C docs html

      - name: "Init new report is dist folder and commit generated files"
        run: |
          cd docs/build/html
          git init
          touch .nojekyll
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "deploy"

      - name: "Force push to destination branch"
        uses: ad-m/github-push-action@v0.5.0"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/build/html
